name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
      - if: matrix.node-version == '16'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{github.token}}
